version: '3.1'
services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8082:8080"
#    depends_on:
#      - db
  db:
    image: "postgres:15"
    restart: always
    environment:
      POSTGRES_DB: currency
      POSTGRES_USER: viki
      POSTGRES_PASSWORD: viki
    ports:
      - "5415:5432"
  rabbitmq:
    image: "rabbitmq:3.9.11-management-alpine"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"